# Generated by Django 4.1.3 on 2022-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
