# Generated by Django 5.0.6 on 2024-07-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(default='#', max_length=2048),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default='#', max_length=256),
        ),
    ]
