# Generated by Django 5.0.6 on 2024-07-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_credential_project_youtube_alter_project_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='description',
            new_name='desc',
        ),
    ]
